const mongoose = require('mongoose');
const Achievements = require('../models/achievement.model');
require('dotenv').config();

const achievements = [
    // Focus Session Achievements
    {
        title: 'First Steps',
        description: 'Complete your first focus session',
        category: 'Focus',
        xp: 50,
        criteria: { type: 'sessions', value: 1 }
    },
    {
        title: 'Focus Apprentice',
        description: 'Complete 10 focus sessions',
        category: 'Focus',
        xp: 100,
        criteria: { type: 'sessions', value: 10 }
    },
    {
        title: 'Focus Warrior',
        description: 'Complete 50 focus sessions',
        category: 'Focus',
        xp: 250,
        criteria: { type: 'sessions', value: 50 }
    },
    {
        title: 'Focus Master',
        description: 'Complete 100 focus sessions',
        category: 'Focus',
        xp: 500,
        criteria: { type: 'sessions', value: 100 }
    },
    {
        title: 'Focus Legend',
        description: 'Complete 500 focus sessions',
        category: 'Focus',
        xp: 1000,
        criteria: { type: 'sessions', value: 500 }
    },

    // Focus Time Achievements
    {
        title: 'Quick Sprint',
        description: 'Accumulate 10 hours of focus time',
        category: 'Focus',
        xp: 100,
        criteria: { type: 'time', value: 600 }
    },
    {
        title: 'Marathon Runner',
        description: 'Accumulate 50 hours of focus time',
        category: 'Focus',
        xp: 400,
        criteria: { type: 'time', value: 3000 }
    },
    {
        title: 'Time Master',
        description: 'Accumulate 100 hours of focus time',
        category: 'Focus',
        xp: 800,
        criteria: { type: 'time', value: 6000 }
    },
    {
        title: 'Endurance Expert',
        description: 'Accumulate 200 hours of focus time',
        category: 'Focus',
        xp: 1200,
        criteria: { type: 'time', value: 12000 }
    },
    {
        title: 'Timeless',
        description: 'Accumulate 1000 hours of focus time',
        category: 'Focus',
        xp: 5000,
        criteria: { type: 'time', value: 60000 }
    },

    // Streak Achievements
    {
        title: 'Habit Builder',
        description: 'Maintain a 7-day habit streak',
        category: 'Streak',
        xp: 150,
        criteria: { type: 'streak', value: 7 }
    },
    {
        title: 'Perfect Week',
        description: 'Complete all habits for 7 days in a row',
        category: 'Streak',
        xp: 300,
        criteria: { type: 'perfect_week', value: 'Perfect Week' }
    },
    {
        title: 'Consistency King',
        description: 'Maintain a 30-day habit streak',
        category: 'Streak',
        xp: 750,
        criteria: { type: 'streak', value: 30 }
    },

    // Task Achievements
    {
        title: 'Task Enthusiast',
        description: 'Complete 10 tasks',
        category: 'Task',
        xp: 75,
        criteria: { type: 'tasks', value: 10 }
    },
    {
        title: 'Task Manager',
        description: 'Complete 50 tasks',
        category: 'Task',
        xp: 200,
        criteria: { type: 'tasks', value: 50 }
    },
    {
        title: 'Knowledge Seeker',
        description: 'Create 50 notes',
        category: 'Task',
        xp: 350,
        criteria: { type: 'notes', value: 50 }
    },
    {
        title: 'Task Crusher',
        description: 'Complete 100 tasks',
        category: 'Task',
        xp: 300,
        criteria: { type: 'tasks', value: 100 }
    },
    {
        title: 'Task Champion',
        description: 'Complete 200 tasks',
        category: 'Task',
        xp: 600,
        criteria: { type: 'tasks', value: 200 }
    },
    {
        title: 'Task Legend',
        description: 'Complete 500 tasks',
        category: 'Task',
        xp: 1200,
        criteria: { type: 'tasks', value: 500 }
    },

    // Level Achievements
    {
        title: 'Rising Star',
        description: 'Reach level 5',
        category: 'Level',
        xp: 250,
        criteria: { type: 'level', value: 5 }
    },
    {
        title: 'Level Up',
        description: 'Reach level 10',
        category: 'Level',
        xp: 500,
        criteria: { type: 'level', value: 10 }
    },
    {
        title: 'High Achiever',
        description: 'Reach level 15',
        category: 'Level',
        xp: 1000,
        criteria: { type: 'level', value: 15 }
    },
    {
        title: 'Level Pro',
        description: 'Reach level 20',
        category: 'Level',
        xp: 1500,
        criteria: { type: 'level', value: 20 }
    },

    // Special Achievements
    {
        title: 'AI Prodigy',
        description: 'Study a set of flashcards generated by the AI Coach',
        category: 'Special',
        xp: 250,
        criteria: { type: 'ai_flashcards', value: 1 }
    },
    {
        title: 'Night Owl',
        description: 'Complete a focus session between midnight and 4 AM',
        category: 'Special',
        xp: 300,
        criteria: { type: 'night_owl', value: 'Night Owl' }
    },
    {
        title: 'Weekend Warrior',
        description: 'Log 5 hours of focus time during a single weekend',
        category: 'Special',
        xp: 400,
        criteria: { type: 'weekend', value: 'Weekend Warrior' }
    },
    {
        title: 'Deep Work',
        description: 'Complete a single focus session of 3 hours or more',
        category: 'Special',
        xp: 750,
        criteria: { type: 'deep_work', value: 'Deep Work' }
    }
];

async function populateAchievements() {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to MongoDB');

        // Clear existing achievements
        await Achievements.deleteMany({});
        console.log('Cleared existing achievements');

        // Insert new achievements
        await Achievements.insertMany(achievements);
        console.log('Successfully populated achievements');

        // Disconnect from MongoDB
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
    } catch (error) {
        console.error('Error populating achievements:', error);
        process.exit(1);
    }
}

populateAchievements();